In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [4]:
pdb_list = []
for i in open('/content/6akv.pdb'):
    pdb_list.append(i)

In [5]:
pdb_string = ''
for i in open('/content/6akv.pdb'):
    pdb_string += i

In [6]:
len(pdb_list)

1709

In [7]:
pdb_list[504]

'ATOM      1  N   ALA A   2     -22.389 -16.207 -13.904  1.00 53.15           N  \n'

In [8]:
pdb_list[1663]

'ATOM   1160  CG2 VAL A 152      -2.656 -25.622 -34.410  1.00 50.84           C  \n'

In [9]:
pdb_atoms = pdb_list[504:1664]

In [10]:
len(pdb_atoms)

1160

In [11]:
pdb_atoms_2 = []
for i in pdb_atoms:
    pdb_atoms_2.append(i.split())
pdb_atoms_2

[['ATOM',
  '1',
  'N',
  'ALA',
  'A',
  '2',
  '-22.389',
  '-16.207',
  '-13.904',
  '1.00',
  '53.15',
  'N'],
 ['ATOM',
  '2',
  'CA',
  'ALA',
  'A',
  '2',
  '-21.565',
  '-16.524',
  '-15.069',
  '1.00',
  '55.92',
  'C'],
 ['ATOM',
  '3',
  'C',
  'ALA',
  'A',
  '2',
  '-20.516',
  '-15.441',
  '-15.330',
  '1.00',
  '60.24',
  'C'],
 ['ATOM',
  '4',
  'O',
  'ALA',
  'A',
  '2',
  '-20.693',
  '-14.279',
  '-14.948',
  '1.00',
  '61.95',
  'O'],
 ['ATOM',
  '5',
  'CB',
  'ALA',
  'A',
  '2',
  '-22.440',
  '-16.719',
  '-16.297',
  '1.00',
  '51.27',
  'C'],
 ['ATOM',
  '6',
  'N',
  'MET',
  'A',
  '3',
  '-19.417',
  '-15.823',
  '-15.976',
  '1.00',
  '61.33',
  'N'],
 ['ATOM',
  '7',
  'CA',
  'MET',
  'A',
  '3',
  '-18.357',
  '-14.888',
  '-16.332',
  '1.00',
  '61.57',
  'C'],
 ['ATOM',
  '8',
  'C',
  'MET',
  'A',
  '3',
  '-18.464',
  '-14.517',
  '-17.805',
  '1.00',
  '51.95',
  'C'],
 ['ATOM',
  '9',
  'O',
  'MET',
  'A',
  '3',
  '-18.835',
  '-15.348',
  '-

In [12]:
pdb_atoms_2_array = np.array(pdb_atoms_2)

In [13]:
pdb_df = pd.DataFrame(pdb_atoms_2, columns =['type','atom_number','atomic_symbol','residue_name','residue_symbol','residue_number','x_axis','y_axis','Z_axis','chain_number','Temperature_factor','atom_symbol_2'] )

In [14]:
pdb_df.head()

type atom_number atomic_symbol residue_name residue_symbol residue_number  \
0  ATOM           1             N          ALA              A              2   
1  ATOM           2            CA          ALA              A              2   
2  ATOM           3             C          ALA              A              2   
3  ATOM           4             O          ALA              A              2   
4  ATOM           5            CB          ALA              A              2   

    x_axis   y_axis   Z_axis chain_number Temperature_factor atom_symbol_2  
0  -22.389  -16.207  -13.904         1.00              53.15             N  
1  -21.565  -16.524  -15.069         1.00              55.92             C  
2  -20.516  -15.441  -15.330         1.00              60.24             C  
3  -20.693  -14.279  -14.948         1.00              61.95             O  
4  -22.440  -16.719  -16.297         1.00              51.27             C

In [15]:
pdb_df.drop(['atom_number','type','chain_number','atom_symbol_2','residue_symbol','Temperature_factor'],axis = 1,inplace = True)
pdb_df.head()

atomic_symbol residue_name residue_number   x_axis   y_axis   Z_axis
0             N          ALA              2  -22.389  -16.207  -13.904
1            CA          ALA              2  -21.565  -16.524  -15.069
2             C          ALA              2  -20.516  -15.441  -15.330
3             O          ALA              2  -20.693  -14.279  -14.948
4            CB          ALA              2  -22.440  -16.719  -16.297

In [16]:
pdb_df.dtypes

atomic_symbol     object
residue_name      object
residue_number    object
x_axis            object
y_axis            object
Z_axis            object
dtype: object

In [17]:
pdb_df = pdb_df.astype({"atomic_symbol": 'category','residue_name': 'category','residue_number':'int','x_axis':'float','y_axis':'float','Z_axis':'float'})

In [18]:
pdb_df.dtypes

atomic_symbol     category
residue_name      category
residue_number       int64
x_axis             float64
y_axis             float64
Z_axis             float64
dtype: object

In [19]:
pdb_df['residue_number'].unique()

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152])

In [20]:
ordinal_label_1 = {k: i for i, k in enumerate(pdb_df['atomic_symbol'].unique(), 1)}
pdb_df['atomic_symbol'] = pdb_df['atomic_symbol'].map(ordinal_label_1)
ordinal_label_2 = {k: i for i, k in enumerate(pdb_df['residue_name'].unique(), 1)}
pdb_df['residue_name'] = pdb_df['residue_name'].map(ordinal_label_2)

In [21]:
ordinal_label_1

{'N': 1,
 'CA': 2,
 'C': 3,
 'O': 4,
 'CB': 5,
 'CG': 6,
 'SD': 7,
 'CE': 8,
 'CD1': 9,
 'CD2': 10,
 'CD': 11,
 'OE1': 12,
 'NE2': 13,
 'OG1': 14,
 'CG2': 15,
 'CG1': 16,
 'OD1': 17,
 'OD2': 18,
 'NZ': 19,
 'ND2': 20,
 'NE': 21,
 'CZ': 22,
 'NH1': 23,
 'NH2': 24,
 'OG': 25,
 'ND1': 26,
 'CE1': 27,
 'CE2': 28,
 'OH': 29,
 'SG': 30,
 'OE2': 31,
 'NE1': 32,
 'CE3': 33,
 'CZ2': 34,
 'CZ3': 35,
 'CH2': 36}

In [22]:
ordinal_label_2

{'ALA': 1,
 'MET': 2,
 'LEU': 3,
 'GLN': 4,
 'THR': 5,
 'ILE': 6,
 'ASP': 7,
 'LYS': 8,
 'ASN': 9,
 'ARG': 10,
 'VAL': 11,
 'SER': 12,
 'GLY': 13,
 'HIS': 14,
 'TYR': 15,
 'CYS': 16,
 'PHE': 17,
 'GLU': 18,
 'PRO': 19,
 'TRP': 20}

In [23]:
pdb_df.head()

atomic_symbol residue_name  residue_number  x_axis  y_axis  Z_axis
0             1            1               2 -22.389 -16.207 -13.904
1             2            1               2 -21.565 -16.524 -15.069
2             3            1               2 -20.516 -15.441 -15.330
3             4            1               2 -20.693 -14.279 -14.948
4             5            1               2 -22.440 -16.719 -16.297

In [24]:
pdb_df = pdb_df

In [25]:
cols = pdb_df.columns.tolist()
cols

['atomic_symbol',
 'residue_name',
 'residue_number',
 'x_axis',
 'y_axis',
 'Z_axis']

In [26]:
cols = cols[1:3]+cols[0:1]+cols[3:]

In [27]:
cols

['residue_name',
 'residue_number',
 'atomic_symbol',
 'x_axis',
 'y_axis',
 'Z_axis']

In [28]:
pdb_df_2 = pdb_df[cols]
pdb_df_2.head()

residue_name  residue_number atomic_symbol  x_axis  y_axis  Z_axis
0            1               2             1 -22.389 -16.207 -13.904
1            1               2             2 -21.565 -16.524 -15.069
2            1               2             3 -20.516 -15.441 -15.330
3            1               2             4 -20.693 -14.279 -14.948
4            1               2             5 -22.440 -16.719 -16.297

In [29]:
pdb_array = np.array(pdb_df_2)
pdb_array.shape

(1160, 6)

In [30]:
pdb_array_demo = pdb_array[:50,:6]

In [31]:
pdb_array_demo.shape

(50, 6)

In [32]:
pdb_array_demo

array([[  1.   ,   2.   ,   1.   , -22.389, -16.207, -13.904],
       [  1.   ,   2.   ,   2.   , -21.565, -16.524, -15.069],
       [  1.   ,   2.   ,   3.   , -20.516, -15.441, -15.33 ],
       [  1.   ,   2.   ,   4.   , -20.693, -14.279, -14.948],
       [  1.   ,   2.   ,   5.   , -22.44 , -16.719, -16.297],
       [  2.   ,   3.   ,   1.   , -19.417, -15.823, -15.976],
       [  2.   ,   3.   ,   2.   , -18.357, -14.888, -16.332],
       [  2.   ,   3.   ,   3.   , -18.464, -14.517, -17.805],
       [  2.   ,   3.   ,   4.   , -18.835, -15.348, -18.642],
       [  2.   ,   3.   ,   5.   , -16.974, -15.478, -16.051],
       [  2.   ,   3.   ,   6.   , -16.655, -15.69 , -14.592],
       [  2.   ,   3.   ,   7.   , -14.91 , -16.114, -14.376],
       [  2.   ,   3.   ,   8.   , -14.149, -14.483, -14.481],
       [  1.   ,   4.   ,   1.   , -18.142, -13.267, -18.121],
       [  1.   ,   4.   ,   2.   , -18.116, -12.852, -19.516],
       [  1.   ,   4.   ,   3.   , -16.831, -13.34 , -2

In [33]:
k = np.random.randint(1,6,size = (50,1))
l = np.random.randint(1,9,size = (50,1))
m = np.random.randint(1,15,size = (50,1))

In [34]:
x = np.array(np.round((np.random.uniform(low=-23, high=-5, size=(50,3))),3))
x

array([[ -5.512, -14.779,  -7.116],
       [-11.023, -16.243, -15.539],
       [-17.617, -16.032, -12.53 ],
       [-16.335, -15.645, -16.265],
       [-19.537,  -9.3  , -10.899],
       [-14.678,  -9.441, -18.953],
       [ -8.379,  -9.697, -21.799],
       [ -8.95 , -15.845, -17.455],
       [-18.44 ,  -8.055,  -7.6  ],
       [-13.638,  -5.447, -22.596],
       [-13.882, -18.622,  -9.822],
       [ -8.528, -22.397, -20.25 ],
       [-12.992, -11.607, -16.747],
       [-12.47 , -13.784, -11.589],
       [-15.396, -17.614, -18.369],
       [ -5.701, -18.583, -11.865],
       [-18.675,  -6.446, -13.457],
       [-19.031, -11.582, -20.592],
       [-18.84 ,  -6.552,  -7.44 ],
       [ -5.273, -11.876, -13.469],
       [-13.558,  -5.156, -10.856],
       [-12.761, -14.34 , -12.573],
       [ -9.928, -17.071, -20.58 ],
       [-19.245, -10.765, -12.9  ],
       [-10.978, -17.303, -10.595],
       [-10.02 ,  -7.7  , -22.214],
       [ -5.737,  -6.206, -20.605],
       [ -6.465, -13.767, -1

In [35]:
x = np.concatenate((k,l,m,x),axis = 1)
x

array([[  3.   ,   5.   ,  10.   ,  -5.512, -14.779,  -7.116],
       [  2.   ,   1.   ,   2.   , -11.023, -16.243, -15.539],
       [  3.   ,   2.   ,   2.   , -17.617, -16.032, -12.53 ],
       [  4.   ,   7.   ,   8.   , -16.335, -15.645, -16.265],
       [  1.   ,   6.   ,   3.   , -19.537,  -9.3  , -10.899],
       [  3.   ,   6.   ,   5.   , -14.678,  -9.441, -18.953],
       [  2.   ,   3.   ,   7.   ,  -8.379,  -9.697, -21.799],
       [  2.   ,   8.   ,  10.   ,  -8.95 , -15.845, -17.455],
       [  4.   ,   2.   ,  10.   , -18.44 ,  -8.055,  -7.6  ],
       [  3.   ,   1.   ,   9.   , -13.638,  -5.447, -22.596],
       [  3.   ,   6.   ,   5.   , -13.882, -18.622,  -9.822],
       [  5.   ,   1.   ,   5.   ,  -8.528, -22.397, -20.25 ],
       [  1.   ,   6.   ,   1.   , -12.992, -11.607, -16.747],
       [  1.   ,   3.   ,  13.   , -12.47 , -13.784, -11.589],
       [  3.   ,   6.   ,   7.   , -15.396, -17.614, -18.369],
       [  3.   ,   3.   ,   8.   ,  -5.701, -18.583, -1

In [36]:
x.shape

(50, 6)

In [37]:
error = (pdb_array_demo - x)**2
error = np.array(np.round(error,3))
error

array([[4.00000e+00, 9.00000e+00, 8.10000e+01, 2.84833e+02, 2.03900e+00,
        4.60770e+01],
       [1.00000e+00, 1.00000e+00, 0.00000e+00, 1.11134e+02, 7.90000e-02,
        2.21000e-01],
       [4.00000e+00, 0.00000e+00, 1.00000e+00, 8.40400e+00, 3.49000e-01,
        7.84000e+00],
       [9.00000e+00, 2.50000e+01, 1.60000e+01, 1.89920e+01, 1.86600e+00,
        1.73400e+00],
       [0.00000e+00, 1.60000e+01, 4.00000e+00, 8.42700e+00, 5.50420e+01,
        2.91380e+01],
       [1.00000e+00, 9.00000e+00, 1.60000e+01, 2.24580e+01, 4.07300e+01,
        8.86300e+00],
       [0.00000e+00, 0.00000e+00, 2.50000e+01, 9.95600e+01, 2.69460e+01,
        2.98880e+01],
       [0.00000e+00, 2.50000e+01, 4.90000e+01, 9.05160e+01, 1.76400e+00,
        1.23000e-01],
       [4.00000e+00, 1.00000e+00, 3.60000e+01, 1.56000e-01, 5.31880e+01,
        1.21926e+02],
       [1.00000e+00, 4.00000e+00, 1.60000e+01, 1.11290e+01, 1.00621e+02,
        4.28370e+01],
       [1.00000e+00, 9.00000e+00, 1.00000e+00, 7.6

In [49]:
class environmnent:
  def __init__(self,orginal,demo):
    self.steps = 2
    self.orginal = orginal
    self.error_1 = np.inf * np.ones(orginal.shape)
    self.error_2 = np.zeros(orginal.shape)
    self.demo = demo
  def error(self):
    self.error_2 = (self.orginal - self.demo)
    return self.error_2
  
  def get_observation(self):
    self.error_2 = self.error()
    return self.demo
    

  def get_action(self):
    #INCREMENT or decrement ALL cell BY +1 or -1

    demo_x = self.demo + np.ones(self.demo.shape)
    self.demo = demo_x
    obs_x = self.get_observation()
    reward_x = self.action()

    demo_y = self.demo - np.ones(self.demo.shape)
    self.demo = demo_y
    obs_y = self.get_observation()
    reward_y = self.action()
    
    if reward_x > reward_y:
      self.demo = demo_x
      return obs_x
    else:
      self.demo = demo_y
      return obs_y

  def is_done(self):
    return self.steps == 0

  def action(self):

    if (self.error_2 <= self.error_1).all():
      reward = 1
    elif(self.error_2[:,:1] <= self.error_1[:,:1]).all():
      reward = 0.6
    elif(self.error_2[:,1:2] <= self.error_1[:,1:2]).all():
      reward = 0.5
    elif(self.error_2[:,2:3] <= self.error_1[:,2:3]).all():
      reward = 0.3
    elif(self.error_2[:,3:] <= self.error_1[:,3:]).all():
      reward = 0.2
    elif(self.error_2[:,:3] <= self.error_1[:,:3]).all():
      reward = 0.6
    if (self.error_2 >= self.error_1).all():
      reward = 0
    
    self.error_1 = self.error_2
    self.steps -= 1

    return reward



In [50]:
class Agent:
  def __init__(self):
     self.total_reward = 0
  
  def steps (self, env: environmnent):
    current_obs = env.get_observation()
    #print(current_obs)
    actions = env.get_action()
    #print(len(actions))
    reward = env.action()
    print(reward)
    self.total_reward += reward

In [51]:
if __name__ == "__main__":
  env = environmnent(pdb_array_demo,x)
  agent = Agent()

  while not env.is_done():
    agent.steps(env)
  print('total reward', agent.total_reward)


Streaming output truncated to the last 5000 lines.
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0.7
0

KeyboardInterrupt: ignored

In [ ]:
x